version: 1
root:
    level: INFO
    handlers: []

loggers:
    slack:
        level: INFO
        handlers: [consoleHandler, fHandler]
        qualname: slackLogger
        propogate: no

    email:
        level: INFO
        handlers: [consoleHandler, fHandler]
        qualname: emailLogger
        propogate: no

    elementTracker:
        level: DEBUG
        handlers: [consoleHandler, fHandler]
        qualname: elementTrackerLogger
        propogate: no

formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    alt:
        format: '%(asctime)s - %(name)s - %(levelname)s'

handlers:
    consoleHandler:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    fHandler:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: 'my.log'
